version: '3'

services:
  app:
    build: .
    image: &khronos
      khronos:dev
    env_file: &khronos_env
      - dev.env
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    command: bash /wait-for-it.sh postgres:5432 -- python app.py
    depends_on:
      - postgres

  celery-worker:
    image: *khronos
    command: bash /wait-for-it.sh postgres:5432 -- celery worker --app=tasks --concurrency=3 --beat --loglevel=INFO
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - app

  postgres:
    image: postgres:10.3-alpine
    restart: always
    env_file: *khronos_env
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0.8-alpine
    command: redis-server
    ports:
      - "6379:6379"
